apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterhub
  labels:
    app: jupyterhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterhub
  template:
    metadata:
      labels:
        app: jupyterhub
    spec:
      containers:
      - name: jupyterhub
        image: jupyterhub/jupyterhub
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: jupyterhub
spec:
  type: NodePort
  selector:
    app: jupyterhub
  ports:
    - port: 8000
      targetPort: 8000
      # nodePort: 30007